### ISSUE TITLE
Why is QSORT faster than SORT?

### ISSUE THREAD

**Issue by tensorturtle** [developer0hye/qsort#1]
Hello,
I am curious to know what improvements you made to SORT.
What details make QSORT so much faster than SORT?

Thank you

Update: nevermind, I see on the README that it skips the kalman filter.

If you need the simplest, fastest tracker, I recommend IOU tracker [https://github.com/bochinski/iou-tracker](https://github.com/bochinski/iou-tracker). 
In my practical use, I found it 20x faster than SORT.

**Comment by developer0hye** [comment]
Hello!

Thanks for your recommendation!  I love algorithms designed for practioners.
